---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      host: longhorn.marms
      hosts:
        - paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: longhorn-frontend
    extraArgs:
      - --set csi.kubeletRootDir="/var/snap/microk8s/common/var/lib/kubelet"
      - --set defaultSettings.defaultDataPath="/tmp/longhorn"