---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: "1.0.x"
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      hosts:
        - host: portainer.marms
          paths:
            - path: /
              pathType: Prefix
