---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers0
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers0
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers1
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers0
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers1
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/addresses
          value:
            - 192.168.10.0/24
      target:
        kind: IPAddressPool
        name: primarypool
        namespace: metallb-system
    - patch: |
        - op: replace
          path: /spec/values/controller/service/loadBalancerIP
          value: 192.168.10.1
      target:
        kind: HelmRelease
        name: nginx
        namespace: ingress-nginx
